title: Recon
description: Blog Personal
theme: just-the-docs

url: https://adrirth.github.io/

# Barra de navegación
nav_enabled: true

# External navigation links
nav_external_links:
  - title: Mi github personal
    url: https://github.com/Adrirth
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


# Tema
color_scheme: foo

# Búsqueda
search_enabled: true
  # Maximum amount of previews per search result
  # Default: 3
search.previews: 3

  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
search.preview_words_before: 5

  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
search.preview_words_after: 10  

# Volver arriba
back_to_top: true
back_to_top_text: "Volver arriba"

# Favicon
favicon_ico: "/assets/images/favicon.ico"

# logo
logo: "/assets/images/logo.png"

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
#gh_edit_link: true # show or hide edit this page link
#gh_edit_link_text: "Edit this page on GitHub."
#gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
#gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
#gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


# Callouts

callouts:
  highlight:
    color: yellow
  important:
    color: yellow
  new:
    title: Nuevo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red
